### ISSUE TITLE
Building the initial code base - Repo is Work In Progress until specified otherwise

### ISSUE THREAD

**Issue by yehuda-naveh** [Qiskit/qiskit-jku-provider#1]
We will now build the initial code base

@azulehner , after accepting the invitation I sent you, please push your code base of the simulator, and @gadial will PR in parallel his wrapper to Qiskit. @azulehner I made you admin, so you should be able to push your initial code, and later approve enhancements to it

The entire code base will be in work-in-progress until smooth integration. Hopefully we'll have the code base ready soon, remove the WIP, and can proceed to enhance it from here.

**Comment by azulehner** [comment]
I have pushed my code base of the simulator

**Comment by gadial** [comment]
Here are detailed instructions for the install and test process for pip users.  We wish to verify this indeed works for Linux computers.

1) **sudo pip uninstall qiskit-addon-jku**
2) **sudo -H pip install qiskit-addon-jku**
3) Run **sudo pip show qiskit-addon-jku** and take a look at the dir given by Location:
	3.1) This directory should have a subdirectory named qiskit_addon_jku (note the underline).
	3.2) This subdir should have the following files: **MakeCache.txt  CMakeFiles  cmake_install.cmake  __init__.py  jkuprovider.py  jku_simulator  Makefile  __pycache__  qasm_simulator_jku.py**
4) Try running on the test files located in the **examples** directory of the github code.
	4.1) **python3 examples/jku_backend.py** (might have to copy the ghz.qasm from the **examples** dir to the working dir)
	4.2) **python3 examples/jku_circuit.py**
5) If it fails, you might need to set PYTHONPATH to point at the correct dirs: **setenv PYTHONPATH <path_to_python_package_dir>/qiskit_addon_jku:<path_to_python_package_dir>/qiskit**

**Comment by yehuda-naveh** [comment]
Closing as we are done for first release and ready for public
