### ISSUE TITLE
Wheel versions for PIP installations

### ISSUE THREAD

**Issue by gadial** [Qiskit/qiskit-jku-provider#10]
Since JKU contains a C++ component (the simulator itself), anyone installing via pip must compile the simulator or use a precompiled binary. I have generated such binaries for Linux, Windows and Mac OSx, and they are to be distributed via a Wheel package. This can be seen [here](https://pypi.org/project/qiskit-addon-jku/#files).

The issue to be considered here is the name of the wheel packages. The correct name determines which wheel is to be installed when the end user clicks `pip install qiskit-addon-jku`.

The wheel name automatically generated when creating a wheel is something of the form `qiskit_addon_jku-1.0.1-cp35-cp35m-win32.whl`. The suffix contains Python information: the "cp35" indicates the Python version (cython 3.5 in this case) and the "win32" component means this is a 32-bit windows installation of Python. For different systems (e.g. Python 3.6 or 64-bit installations) I cannot guarantee the wheel will install simply due to the "wrong" name.

I could not find a comprehensive reference as to how to "correctly" name a package; whether we should create a package for each combination of Python version/bits/operating system or is there a way to create a more "universal" package. A "universal" name for example is `qiskit_addon_jku-1.0.1-cp36-none-any.whl`, but this is **too** universal since it is operating-system independent (whereas our JKU compilation is not).

**Comment by yehuda-naveh** [comment]
The pip issues where resolved
