### ISSUE TITLE
Samples out of date

### ISSUE THREAD

**Issue by ValentinS4t1qbit** [Qiskit/qiskit-jku-provider#15]
Hello,

I am trying to run some qiskit samples to test the JKU simulator, but I get errors. Could you please provide me with the latest versions of Qiskit these were tested and validated ? I would like to try this simulator (I understand that JKU is BDD-based?).

I currently cannot run the following sample (**sample 1**):
https://github.com/Qiskit/qiskit-jku-provider/blob/master/examples/jku_circuit.py

... or the main thing I want to run, **sample 2**, relying on qiskit_chemistry (eventually yields same error than sample 1 after a few fixes)
https://github.com/Qiskit/qiskit-chemistry/blob/master/qiskit_aqua_chemistry/drivers/pyscfd/README.md (with JKU as backend)

If you have a way for me to test / benchmark JKU that does not require the resolution of the errors described below, that would be useful on the very short-term (that being said I think it's very important that users are able to run your samples without troubles !)

========================================================

**1 - Environment**

Here is my current Qiskit environment, which I believe has the latest version of everything (`pip freeze`):
```
qiskit==0.7.2
qiskit-addon-jku==1.0.2
qiskit-aer==0.1.1
qiskit-aqua==0.4.1
qiskit-aqua-chemistry==0.4.0
qiskit-chemistry==0.4.2
qiskit-terra==0.7.0
```

**2 - Error**

For both samples, I eventually get a key error, raised in function `compute_measurement_data`: I have stopped investigating after reaching that point.
```
  File "/home/vsenicourt/Desktop/virtualenvs/simulators/lib/python3.6/site-packages/qiskit_addon_jku/qasm_simulator_jku.py", line 243, in compute_measurement_data
    measurement_data['mapping'][op['qubits'][0]] = op['clbits'][0]
KeyError: 'clbits'
```

Before reaching this error, a few straightforward ones appeared. For both these samples I'm running, a few namespaces have changed for the latest Qiskit:
- In the "main" files, I need to import `qiskit_addon_jku` (and not `qiskit_jku_provider`)
- `qiskit.backends` does not exist anymore. You have to go through `qiskit.providers` for various imports in **qasm_simulator_JKU.py**(a search in their Github for the classes you need to import solves it)

Several errors occurred in the main qiskit / qiskit_aqua modules in **sample 2**:
Qiskit accesses "configuration information" through a method that apparently returns an object and reads the fields, while the JKU package tries to access a dictionary whose name iOS preceded by "_". Example:
```
backend.configuration().simulator. # Latest Qiskit
backend._configuration['simulator'] # Latest JKU
```

After solving these kinds of error, I eventually reach the code section that returns the error I shared at the top of this post, the "key" error, for both samples. It would seem that the keys and values of the dictionaries used to created `header` and `ops` are not as expected: maybe you guys were relying on qiskit to build them and their implementation has changed since then. As a consequence, the  dictionary `obj_circuit` passed is not matching the fields the `compute_measurement_data` function is expecting.

Thanks for your efforts ! Again, If you guys were just able to point at the latest Qiskit environment (versions) your samples were tested and working, that would already allow me to try your simulator :)

**Comment by yehuda-naveh** [comment]
Talking with @gadial seems this was fixed since, but Gadi will check again and comment

**Comment by gadial** [comment]
Thank you for your excellent feedback! We have just uploaded a new version of the JKU provider to PyPi and I hope all the problems you have raised were addressed. I explicitly verified that our samples work now with qiskit 0.7.2.

One thing I did not manage to check is working with Aqua; if you still encounter problems let us know.
