### ISSUE TITLE
backend.status()

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-jku-provider#23]
This might be actually a terra issue. @diego-plan9 and @ajavadia we need to decide on this. My view is I think backend.status() should not be required and be optional for remote backends. I know we may have discussed it to be required but this does not really make sense for a local backend. I am sure @atilag will agree with me on this :-). 

This being said assuming it is is required then when i run 

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/15731369/52982168-87f9c880-33b2-11e9-8ff3-3ecbc59eba95.png">

I think this is giving the qiskit-terra version, not the JKU version. So if we are going to keep status in local then we need to update the version. 

Let's assume that we keep it in local then pending_job should not be required it should be just optional that you add for a backend that has a queue. Second, if the status message is empty should we show it?

**Comment by diego-plan9** [comment]
Hmm, then we are talking about a specs change indeed! For simplicity (in the bureocracy deparment), I'd go for the quick fix of making `jku_backend` provide the right version (probably by implementing the method itself, with a variation of https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/basebackend.py#L71-L81), and move the discussion about the backend status being required or not to the terra repo.

**Comment by jaygambetta** [comment]
If we implement the method we don’t need to add the pending jobs. If this is correct then I’m good we can keep it as required.  The reason I don’t like pending jobs is if I run 100 job locally and then look this does not update as there is no queue.

**Comment by jaygambetta** [comment]
Don’t worry I see the above is not possible as it’s in the marshmallow schema.

**Comment by yehuda-naveh** [comment]
Can we close this here?

**Comment by jaygambetta** [comment]
We need to just update the backend status method to have the name fixed and the version taking from this repo not terra.

**Comment by gadial** [comment]
Fixed in #48.
