### ISSUE TITLE
when we are done we should make a tag release to go with the pip version. 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-jku-provider#25]

**Comment by gadial** [comment]
I think we are ready now as soon as we close #27. Do you want me to create the tag?

**Comment by jaygambetta** [comment]
quick look i think we need to update the read me with the sting name

**Comment by diego-plan9** [comment]
Yes, in general we tend to make it the "very last thing" (ie, after the package is uploaded to pip, and everything else is 100% ready) - this way each release of pip is ensured to contain the same sources as the corresponding github release.

**Comment by yehuda-naveh** [comment]
All is ready, pip versions uploaded for Windows, Mac, Linux. Tagged version 0.1.1
