### ISSUE TITLE
test should cover the same basic aer (without the statevector and unitary)

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-jku-provider#27]
https://github.com/Qiskit/qiskit-terra/tree/master/test/python/basicaer and the test folder should be names test not test_jku. I would replace them with test taken from basicaer (updated for JKU) @diego-plan9 it would be nice to have these as default simulator ones somehow. Maybe we can make a copy get it passing, set up travis and then make an issue for an automated simulator test set.

**Comment by jaygambetta** [comment]
The one test there that needs to be check is the tensor order.

**Comment by yehuda-naveh** [comment]
Apart from having a default test-suite for all simulators, Gadi will add some additional unit tests for now, and then we can change this into enhancement tag. JKU does produce a statevector, so some statevector tests as well.

**Comment by yehuda-naveh** [comment]
@diego-plan9 are you fine with the tests you added or do you want us to add more unit tests before first release?

**Comment by diego-plan9** [comment]
> @diego-plan9 are you fine with the tests you added or do you want us to add more unit tests before first release?

Pinging  @jaygambetta ! The test I added just cover "basic provider and backend functionality" in regards to the needs of being compatible with terra, I did not include any tests covering actual JKU-specific functionality, and mostly relied on the existing tests.

**Comment by yehuda-naveh** [comment]
never mind, @gadial just added the statevector unit-test and will probably add more soon, so we'll have also the JKU-specific

**Comment by gadial** [comment]
After merging both #53  (already done) and #54 I think we can close this.
