### ISSUE TITLE
JKU provider downgrades terra version

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-jku-provider#63]
### Informations

- **Qiskit-JKU-Provider version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
In testing installing from source the dev versions of all packages for qiskit 0.9, I have found the installing the JKU provider downgrades terra from 0.8 -> 0.7.2 (the latest pip).  This then breaks the installation of `aer` and the `ibmq-provider`.  One must reinstall terra from source, and then `ibmq-provider` from source.

**Comment by yehuda-naveh** [comment]
@nonhermitian please confirm if #65  solves this and #64 for now. If so can close, otherwise @gadial is taking a deeper look

**Comment by nonhermitian** [comment]
It will.

**Comment by yehuda-naveh** [comment]
by #65
