### ISSUE TITLE
JKU provider not compatible with terra 0.8

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-jku-provider#64]
### Informations

- **Qiskit-JKU-Provider version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python
from qiskit_jku_provider import JKUProvider
```
gives
```python

ImportError: cannot import name 'QISKitError' from 'qiskit' (/miniconda3/envs/testing/lib/python3.7/site-packages/qiskit_terra-0.8.0-py3.7-macosx-10.7-x86_64.egg/qiskit/__init__.py)
```

**Comment by yehuda-naveh** [comment]
by #65

**Comment by jaygambetta** [comment]
this is not fixed.

**Comment by jaygambetta** [comment]
@yehuda-naveh and @mtreinish I think we need change QISKitError to QiskitError and then make a new pip release. 

This is the 

/anaconda3/envs/QiskitDevenv/lib/python3.7/site-packages/qiskit_jku_provider/jkusimulatorerror.py in <module>
     10 """
     11 
---> 12 from qiskit import QISKitError
     13 
     14 

ImportError: cannot import name 'QISKitError' from 'qiskit' (/anaconda3/envs/QiskitDevenv/lib/python3.7/site-packages/qiskit/__init__.py)

**Comment by yehuda-naveh** [comment]
@gadial let's go carefully over all potential incompatibilities with 0.8, then put the new pip

**Comment by jaygambetta** [comment]
Did we check the pip version

**Comment by yehuda-naveh** [comment]
We'll make a new pip. I'd like @gadial to go over all potential incompatibilities with 0.8, and then the pip

**Comment by gadial** [comment]
I updated some of the code so we'll have no deprecation warnings (or failing tests) and uploaded a new pip  for Windows/Linux/Mac
