### ISSUE TITLE
Update for terra 0.6

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-jku-provider#7]
Following a conversation with @yehuda-naveh , I'm opening the issue to track the work needed for updating the backend to work with the upcoming terra 0.6. The plan is to follow the work done in the sympy and projectq repositories:
- [x] create a `release/0.6` branch, to ensure the changes are isolated there until 0.6 is out.
- [ ] update the addon for qobj (updating the functions that accept a qobj (`run()`) and return a result.
- [ ] update the addon for the new module structure

Finally, the branch will be merged with `master` and the new pip package should be generated once everything else is in place (and coordinated with the terra 0.6 release).

**Comment by yehuda-naveh** [comment]
updated by now to 0.7.2 by #17
